// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"github.com/zrcoder/cdor"
	"os"
)

const _ = true

//line cmd/cdor/main.gop:7
func main() {
//line cmd/cdor/main.gop:7:1
	data, _ := cdor.Ctx().Cons(cdor.Con("Go+", "Go", cdor.Opt().Label("cdor"))).Gen()
//line cmd/cdor/main.gop:13:1
	os.WriteFile("hello.svg", data, 0600)
}
