// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/zrcoder/cdor"

const _ = true

type App struct {
	cdor.App
}
//line usage/single/main_cdor.gox:1
func (this *App) MainEntry() {
//line usage/single/main_cdor.gox:1:1
	this.Con("x", "y")
//line usage/single/main_cdor.gox:3:1
	this.SaveFile("single.svg")
}
func main() {
	cdor.Gopt_App_Main(new(App))
}
