// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/zrcoder/cdor"

const _ = true

type hi1 struct {
	cdor.Cdor
	*App
}
type hi2 struct {
	cdor.Cdor
	*App
}
type App struct {
	cdor.App
}
//line usage/merge/main_cdor.gox:1
func (this *App) MainEntry() {
//line usage/merge/main_cdor.gox:1:1
	this.Con("a", "x")
//line usage/merge/main_cdor.gox:2:1
	this.Merge()
//line usage/merge/main_cdor.gox:3:1
	this.SaveFile("merged.svg")
}
func main() {
	cdor.Gopt_App_Main(new(App), new(hi1), new(hi2))
}
//line usage/merge/hi1_cdor.gox:1
func (this *hi1) Main() {
//line usage/merge/hi1_cdor.gox:1:1
	this.Con("x", "y")
}
//line usage/merge/hi2_cdor.gox:1
func (this *hi2) Main() {
//line usage/merge/hi2_cdor.gox:1:1
	this.Con("a", "b")
}
